version: '3.7'

services:
  db:
    container_name: orclist_db
    image: mongo:latest
    restart: always
    command: mongod --quiet --logpath /dev/null
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/database
    environment: 
      - MONGO_INITDB_DATABASE= Orclist
  