version: '3.7'

services:
  mongo:
    container_name: orclist_db
    image: mongo
    command: mongod --quiet --logpath /dev/null

  backend:
    container_name: orclist_backend
    command: yarn dev
    environment:
      - DATABASE_URL=mongodb://orclist_db/orclist
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5050:5050'
    depends_on: 
      - mongo
    volumes:
        - ./backend:/app
        - /app/node_modules

  frontend:
    container_name: orclist_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/frontend'
      - '/frontend/node_modules'
    ports: 
      - '1234:1234'
    environment: 
      - NODE_ENV=development